### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by idkmew** [YogaSakti/imageToSticker#109]
(node:3408) UnhandledPromiseRejectionWarning: TypeError: fromBuffer is not a function
    at D:\MathType\Whatsapp\wa-bot.js-master\utils\fetcher.js:73:31
    at new Promise (<anonymous>)
    at uploadImages (D:\MathType\Whatsapp\wa-bot.js-master\utils\fetcher.js:72:12)
    at D:\MathType\Whatsapp\wa-bot.js-master\index.js:679:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Page._onBindingCalled (D:\MathType\Whatsapp\wa-bot.js-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:747:28)
(node:3408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Ad yg tau cara atasiny?

**Comment by idkmew** [comment]
> (node:3408) UnhandledPromiseRejectionWarning: TypeError: fromBuffer is not a function
> at D:\MathType\Whatsapp\wa-bot.js-master\utils\fetcher.js:73:31
> at new Promise ()
> at uploadImages (D:\MathType\Whatsapp\wa-bot.js-master\utils\fetcher.js:72:12)
> at D:\MathType\Whatsapp\wa-bot.js-master\index.js:679:38
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async Page._onBindingCalled (D:\MathType\Whatsapp\wa-bot.js-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:747:28)
> (node:3408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> 
> Ad yg tau cara atasiny?

dibagian Create Custom meme (top text & bottom text)
