### ISSUE TITLE
project error

### ISSUE THREAD

**Issue by KINGMAN1996** [YogaSakti/imageToSticker#119]
npm start

> whatsapp-bot-sticker-creator@10.0.0 start /home/runner/imageToSticker
> node index.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- /home/runner/imageToSticker/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/imageToSticker/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/imageToSticker/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot-sticker-creator@10.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whatsapp-bot-sticker-creator@10.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-08T15_45_03_441Z-debug.log
exit status 1

**Comment by KINGMAN1996** [comment]
its work

**Comment by TentacleSama4254** [comment]
how

**Comment by Nurutomo** [comment]
npm i @open-wa/wa-automate
