### ISSUE TITLE
Heroku TypeError: Cannot read property 'name' of undefined at /app/lib/downloader.js:19:67

### ISSUE THREAD

**Issue by ginapple** [YogaSakti/imageToSticker#133]
Heroku logs:
2021-02-10T02:08:26.990614+00:00 app[worker.1]: [EXEC] 10/02/21 09:08:26 tiktok [1] from‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎
2021-02-10T02:08:27.523936+00:00 app[worker.1]: Get metadata from => https://www.tiktok.com/@itsandani/video/6869248690381425922
2021-02-10T02:08:28.040386+00:00 app[worker.1]: TypeError: Cannot read property 'name' of undefined
2021-02-10T02:08:28.040396+00:00 app[worker.1]:     at /app/lib/downloader.js:19:67

sticker sama resi jalan, tapi lainnya enggak jalan(downloader, meme, translate)
kurang apa ya?

**Comment by juwenaja** [comment]
dah mati semua gan
