### ISSUE TITLE
I did everyhing perfect but..

### ISSUE THREAD

**Issue by DerMarsi** [YogaSakti/imageToSticker#136]
i get this;

└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(node:4922) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (/home/kali/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:172:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/kali/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
(node:4922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jrgdiaz** [comment]
Getting same error here!

**Comment by jrgdiaz** [comment]
I installed latest version of @open-wa/wa-automate 3.6.10 and it's working again!

**Comment by ajipw** [comment]
Hi, I get this error too, 

And then I try to update with
`npm update`

And it working again
