### ISSUE TITLE
Error tiktok dan twitter

### ISSUE THREAD

**Issue by Viole403** [YogaSakti/imageToSticker#21]
Saat mencoba tiktok donwloader mendapat error
```javascript
Something went wrong Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat] (https://web.whatsapp.com/app2.cbf33baa693d058583d8.js:2:421426)
    at /home/yuzusa/bot/imageToSticker/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1536:25
    at async /home/yuzusa/bot/imageToSticker/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1533:16
    at ExecutionContext._evaluateInternal (/home/yuzusa/bot/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/yuzusa/bot/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
Caught exception:  Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat] (https://web.whatsapp.com/app2.cbf33baa693d058583d8.js:2:421426)
    at /home/yuzusa/bot/imageToSticker/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1536:25
    at async /home/yuzusa/bot/imageToSticker/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1533:16
    at ExecutionContext._evaluateInternal (/home/yuzusa/bot/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/yuzusa/bot/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```
Dan saat mencoba twitter donwloader dapat respon
```bash
[EXEC] 13/08 23:43:07 twt (1) from Lara
Get Twitter video metadata....
```
tetapi tidak muncul result lainnya dan di client juga tidak ada respon hasil dari downloadernya

**Comment by Viole403** [comment]
Note: i use last version

**Comment by YogaSakti** [comment]
install google chrome and replace `serverOption['browserRevision'] = .....` with `serverOption['executablePath'] = '/usr/bin/google-chrome';` on index.js
