### ISSUE TITLE
Instagram Donwloader error

### ISSUE THREAD

**Issue by rebahanelite** [YogaSakti/imageToSticker#50]
![image](https://user-images.githubusercontent.com/68410598/92502202-bb68a600-f229-11ea-9176-8e23cae22e0a.png)
Kenapa ya om?

**Comment by fnbots-wa** [comment]
jejak

**Comment by YogaSakti** [comment]
Link yang mau lu download mana?

**Comment by fnbots-wa** [comment]
Get Instagram metadata....
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/root/bot/node_modules/video-url-link/lib/instagram/index.js:17:31)
    at Request.self.callback (/root/bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/root/bot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Gunzip.<anonymous> (/root/bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at Gunzip.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1244:12)


ini error kalo url ada httpsnya.. langsung exit terminalnya

**Comment by fnbots-wa** [comment]
Get Instagram metadata....
Error: Invalid URI "instagram.com/p/CBNRA6olSE8/?igshid=x0yxwa53uxad?__a=1"
    at Request.init (/root/bot/node_modules/request/request.js:273:31)
    at new Request (/root/bot/node_modules/request/request.js:127:8)
    at request (/root/bot/node_modules/request/index.js:53:10)
    at exports.getInfo (/root/bot/node_modules/video-url-link/lib/instagram/index.js:15:5)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at /root/bot/lib/dl-video.js:21:5
    at new Promise (<anonymous>)
    at instagram (/root/bot/lib/dl-video.js:19:28)


ini error kalo gapake https://, langsung instagram.com aja

**Comment by YogaSakti** [comment]
![image](https://user-images.githubusercontent.com/24309806/92563133-46d14e00-f2a1-11ea-864f-672c8a37c5af.png)
gada masalah @fnbots-wa

**Comment by fnbots-wa** [comment]
> ![image](https://user-images.githubusercontent.com/24309806/92563133-46d14e00-f2a1-11ea-864f-672c8a37c5af.png)
> gada masalah @fnbots-wa 

coba dari indexnya. bukan dari downloadernya.

**Comment by fnbots-wa** [comment]
![image](https://user-images.githubusercontent.com/70086013/92566969-37550380-f2a7-11ea-8b4c-0f17b62775f9.png)
check...

**Comment by dzakijo1** [comment]
ane sebelumnya ga make rdp, cuma run di laptop doang, work ig downloadernya, pas ane run di rdp baru error..

**Comment by YogaSakti** [comment]
iya, instagram sensitive banget sama ip, gw run di laptop gw juga aman aman aja.

**Comment by dzakijo1** [comment]
ane make ini work buat di RDP..

case 'ig':
            if (args.length >= 1) {
                var param = body.substring(body.indexOf(' '), body.length)
                try {
                    client.reply(from, 'Tunggu sebentar, sedang di proses..', message.id)
                    const resp = await get.get('https://villahollanda.com/api.php?url='+ param).json()
                    console.log(resp)
                    if (resp.mediatype == 'photo') {
                        var ext = '.png'
                    }else{
                        var ext = '.mp4'
                    }
                        client.sendFileFromUrl(from, resp.descriptionc, `igeh${ext}`)
                } catch {
                    client.reply(from, 'Terjadi kesalahan!')
                    }
                }
            break

**Comment by hansputera** [comment]
> iya, instagram sensitive banget sama ip, gw run di laptop gw juga aman aman aja.

pake proxy rotator aja, mungkin bsa

**Comment by btenay4** [comment]
> 
> 
> ane make ini work buat di RDP..
> 
> case 'ig':
> if (args.length >= 1) {
> var param = body.substring(body.indexOf(' '), body.length)
> try {
> client.reply(from, 'Tunggu sebentar, sedang di proses..', message.id)
> const resp = await get.get('https://villahollanda.com/api.php?url='+ param).json()
> console.log(resp)
> if (resp.mediatype == 'photo') {
> var ext = '.png'
> }else{
> var ext = '.mp4'
> }
> client.sendFileFromUrl(from, resp.descriptionc, `igeh${ext}`)
> } catch {
> client.reply(from, 'Terjadi kesalahan!')
> }
> }
> break

ada refrensi ga gan dimana belajar get data api kayak gini , ane mau buat pakek Api yg lain

**Comment by YogaSakti** [comment]
> > iya, instagram sensitive banget sama ip, gw run di laptop gw juga aman aman aja.
> 
> pake proxy rotator aja, mungkin bsa

gak ngaruh wkwkwk

**Comment by fnbots-wa** [comment]
> > ane make ini work buat di RDP..
> > case 'ig':
> > if (args.length >= 1) {
> > var param = body.substring(body.indexOf(' '), body.length)
> > try {
> > client.reply(from, 'Tunggu sebentar, sedang di proses..', message.id)
> > const resp = await get.get('https://villahollanda.com/api.php?url='+ param).json()
> > console.log(resp)
> > if (resp.mediatype == 'photo') {
> > var ext = '.png'
> > }else{
> > var ext = '.mp4'
> > }
> > client.sendFileFromUrl(from, resp.descriptionc, `igeh${ext}`)
> > } catch {
> > client.reply(from, 'Terjadi kesalahan!')
> > }
> > }
> > break
> 
> ada refrensi ga gan dimana belajar get data api kayak gini , ane mau buat pakek Api yg lain

tanya erpan mek, atau @riorenata

**Comment by YogaSakti** [comment]
ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama

**Comment by hansputera** [comment]
> ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama

kalau mau, pakai cookie sih untuk nusbol.

**Comment by dzakijo1** [comment]
> ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama

iya ganti brainly ama pinterest ae wqwqwq

**Comment by hansputera** [comment]
> > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> 
> iya ganti brainly ama pinterest ae wqwqwq

udh ada module wqwqwq

**Comment by hansputera** [comment]
tapi bisa juga sih, cuman bikin opsi negara. Brainly kan ada di banyak negara

**Comment by YogaSakti** [comment]
> > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> 
> kalau mau, pakai cookie sih untuk nusbol.

udah nyoba pake cookie tetep kena login wkwkwk


> > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> 
> iya ganti brainly ama pinterest ae wqwqwq

brainly sih oke, cuman kalo pinterest buat apa?

**Comment by dzakijo1** [comment]
> brainly sih oke, cuman kalo pinterest buat apa?

oh brainly ae om :v

**Comment by hansputera** [comment]
> > > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> > 
> > 
> > kalau mau, pakai cookie sih untuk nusbol.
> 
> udah nyoba pake cookie tetep kena login wkwkwk
> 
> > > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> > 
> > 
> > iya ganti brainly ama pinterest ae wqwqwq
> 
> brainly sih oke, cuman kalo pinterest buat apa?

saya berhasil nusbol wkkwkwkwkwk

**Comment by btenay4** [comment]
> 
> 
> > > ane make ini work buat di RDP..
> > > case 'ig':
> > > if (args.length >= 1) {
> > > var param = body.substring(body.indexOf(' '), body.length)
> > > try {
> > > client.reply(from, 'Tunggu sebentar, sedang di proses..', message.id)
> > > const resp = await get.get('https://villahollanda.com/api.php?url='+ param).json()
> > > console.log(resp)
> > > if (resp.mediatype == 'photo') {
> > > var ext = '.png'
> > > }else{
> > > var ext = '.mp4'
> > > }
> > > client.sendFileFromUrl(from, resp.descriptionc, `igeh${ext}`)
> > > } catch {
> > > client.reply(from, 'Terjadi kesalahan!')
> > > }
> > > }
> > > break
> > 
> > 
> > ada refrensi ga gan dimana belajar get data api kayak gini , ane mau buat pakek Api yg lain
> 
> tanya erpan mek, atau @maderio

ini lu yg kebotan line ama gw dulu ya , asu ga sadar wkwkwkw

**Comment by NaufalCream11** [comment]
> > > ig hapus aja kali ya, ini gabakal beres wkwkwk ganemu rest api buat scrapernya. males kalo harus scrape dari web gitu, berat + lama
> > 
> > 
> > iya ganti brainly ama pinterest ae wqwqwq
> 
> udh ada module wqwqwq

udh ada brainly ama pinterest wqwqwq

**Comment by dzakijo1** [comment]
wqwq hapus IG dah om:v ganti brainly sama itu tuh, fitur sapaan buat yang gabung ke grup:v

**Comment by YogaSakti** [comment]
udah nyobain pake https://github.com/jlobos/instagram-web-api
kalo di vps tetep mental wkwkwk
![image](https://user-images.githubusercontent.com/24309806/93709276-51c09400-fb67-11ea-93d4-e6e1b3ab14c2.png)


> wqwq hapus IG dah om:v ganti brainly sama itu tuh, fitur sapaan buat yang gabung ke grup:v
@dzakijo1  welcome message kan ada tuh di index.js 
![image](https://user-images.githubusercontent.com/24309806/93709291-73ba1680-fb67-11ea-9eb6-fdecf8e6a4d9.png)

**Comment by btenay4** [comment]
gw pakek ini di vps work sih , tapi ga support carousel


case 'instagram':
            if (args.length !== 1) return client.reply(from, 'Maaf, format pesan salah silahkan periksa menu. [Wrong Format]', id)
            const axios = require('axios').default;
            client.reply(from, '_Scraping Metadata..._ ', message.id)
            axios.get('https://villahollanda.com/api.php?url='+ args[0])
            .then(function (response) {
                console.log('IG : ' + args[0])
                if(response.data.descriptionc == null){
                    client.reply(from, '_Maaf Link tidak valid Atau User Privare_',id)
                }
                else if(response.data.mediatype == 'photo'){
                    client.sendFileFromUrl(from, response.data.descriptionc)
                }
                else if(response.data.mediatype == 'video'){
                    client.sendFileFromUrl(from, response.data.descriptionc, 'video.mp4', `Processed for ${processTime(t, moment())} _Second_`, null, null, true)
                }
            })
            .catch(function(error){
                console.log(error)
                client.reply(from, '_Maaf Link tidak valid Atau User Privare_',id)
            })
            break

**Comment by YogaSakti** [comment]
@btenay4 ya masalahnya gasupport carousel kan

**Comment by dzakijo1** [comment]
case 'instagram':
            case 'ig':
            if (args.length >= 1) {
                var param = body.substring(body.indexOf(' '), body.length)
                try {
                    client.reply(from, 'Tunggu sebentar, sedang di proses..', message.id)
                    const resp = await get.get('https://villahollanda.com/api.php?url='+ param).json()
                    console.log(resp)
                    if (resp.mediatype == 'photo') {
                        var ext = '.png'
                    }else{
                        var ext = '.mp4'
                    }
                        client.sendFileFromUrl(from, resp.descriptionc, `igeh${ext}`)
                } catch {
                    client.reply(from, 'Terjadi kesalahan!')
                    }
                }
            break

**Comment by dzakijo1** [comment]
> gw pakek ini di vps work sih , tapi ga support carousel
> 
> case 'instagram':
> if (args.length !== 1) return client.reply(from, 'Maaf, format pesan salah silahkan periksa menu. [Wrong Format]', id)
> const axios = require('axios').default;
> client.reply(from, '_Scraping Metadata..._ ', message.id)
> axios.get('https://villahollanda.com/api.php?url='+ args[0])
> .then(function (response) {
> console.log('IG : ' + args[0])
> if(response.data.descriptionc == null){
> client.reply(from, '_Maaf Link tidak valid Atau User Privare_',id)
> }
> else if(response.data.mediatype == 'photo'){
> client.sendFileFromUrl(from, response.data.descriptionc)
> }
> else if(response.data.mediatype == 'video'){
> client.sendFileFromUrl(from, response.data.descriptionc, 'video.mp4', `Processed for ${processTime(t, moment())} _Second_`, null, null, true)
> }
> })
> .catch(function(error){
> console.log(error)
> client.reply(from, '_Maaf Link tidak valid Atau User Privare_',id)
> })
> break

sama ane make ini juga, noh comment diatas:v

**Comment by aidilaryanto** [comment]
![IG](https://user-images.githubusercontent.com/57789597/94141786-dda42a00-fe9f-11ea-93f4-a6e74304213b.PNG)

Help

**Comment by fdciabdul** [comment]
@YogaSakti API nya pake ini aja 
gabakalan kena block CORS , kalo pake library emang sering gitu si kalo run di VPS / RDP 

http://api.fdci.se/sosmed/insta.php?url=https://www.instagram.com/p/CFWeUn-nUOh/?utm_source=ig_web_copy_link

**Comment by fdciabdul** [comment]
atau kalo mau yang support cs bisa pake ini 🤔

https://github.com/fdciabdul/Instagram-Fetcher

**Comment by YogaSakti** [comment]
> @YogaSakti API nya pake ini aja
> gabakalan kena block CORS , kalo pake library emang sering gitu si kalo run di VPS / RDP
> 
> http://api.fdci.se/sosmed/insta.php?url=https://www.instagram.com/p/CFWeUn-nUOh/?utm_source=ig_web_copy_link

gabisa carousel? skip deh hehehe

**Comment by Nurutomo** [comment]
> ![IG](https://user-images.githubusercontent.com/57789597/94141786-dda42a00-fe9f-11ea-93f4-a6e74304213b.PNG)
> 
> Help

mungkin itu data `html` tapi di `JSON.parse` jadi error.
kamu bisa pake module `jsdom` kalo parse HTML

**Comment by restugbk** [comment]
mampir https://api.i-tech.id/
