### ISSUE TITLE
Something went wrong Error: Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by fnbots-wa** [YogaSakti/imageToSticker#54]
Something went wrong Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ExecutionContext._evaluateInternal (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
    at DOMWorld.evaluate (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:79:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ExecutionContext._evaluateInternal (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
    at DOMWorld.evaluate (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:79:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by fnbots-wa** [comment]
kalo pas mau command sticker, pasti ada error begini, kenapa ya? ada cara fixnya?

**Comment by YogaSakti** [comment]
error di puppeternya, gapaham tanya di reponya open-wa aja
