### ISSUE TITLE
KALO RUN INSTAGRAM DOWNLOADER BOTNYA MATI(ERROR)

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [YogaSakti/imageToSticker#55]
Ini gimana ya bang, kalo gini, kalo pake ig downloader botnya langsung error{mati}

![Capure](https://user-images.githubusercontent.com/58540890/92747936-dd3f6580-f3ae-11ea-9570-871f7156ca1f.PNG)

Get Instagram video metadata....
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\RELFAIZ\imageToSticker\node_modules\video-url-link\lib\instagram\index.js:17:31)
    at Request.self.callback (C:\Users\RELFAIZ\imageToSticker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (C:\Users\RELFAIZ\imageToSticker\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Gunzip.<anonymous> (C:\Users\RELFAIZ\imageToSticker\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at Gunzip.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot-sticker-creator@5.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot-sticker-creator@5.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RELFAIZ\AppData\Roaming\npm-cache\_logs\2020-09-10T14_50_57_601Z-debug.log

padahal semuanya udah install

mohon bantuannya bang!!!

ini no wa saya kalo mau jelasin di wa
0812-1908-7237
wa.me/6281219087237

**Comment by fnbots-wa** [comment]
#50 baca disini biar gak numpuk issue dengan masalah yang sama...

**Comment by MFarelSyahtiawan** [comment]
Lalu, Apa Yang Harus Gw Lakukan?

**Comment by mazrizal-id** [comment]
> Lalu, Apa Yang Harus Gw Lakukan?

Sabar Tunggu devnya ngefix

**Comment by MFarelSyahtiawan** [comment]
Ok
