### ISSUE TITLE
ko pas npm install ngga bisa ya ?

### ISSUE THREAD

**Issue by HansFarhan** [YogaSakti/imageToSticker#60]
pass npm i ada tulisan seperti ini npm WARN tar ENOENT: no such file or directory, open 'C:\bot\imageToSticker-master\node_modules\.staging\async-180db98e\internal\Heap.js'  itu knp ya ?

**Comment by YogaSakti** [comment]
delete package-lock.json

**Comment by HansFarhan** [comment]
> delete package-lock.json

malah kaya gini npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported  itu knp ?

**Comment by YogaSakti** [comment]
gapapa itu, gada masalah

**Comment by HansFarhan** [comment]
> 
> 
> gapapa itu, gada masalah

tpi pas gw npm start gini   

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\bot\imageToSticker-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\bot\imageToSticker-master\index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\bot\\imageToSticker-master\\index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot-sticker-creator@10.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot-sticker-creator@10.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?



itu knp ?

**Comment by MFarelSyahtiawan** [comment]
> > gapapa itu, gada masalah
> 
> tpi pas gw npm start gini
> 
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module '@open-wa/wa-automate'
> Require stack:
> 
> * C:\bot\imageToSticker-master\index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>   at Module.require (internal/modules/cjs/loader.js:1025:19)
>   at require (internal/modules/cjs/helpers.js:72:18)
>   at Object. (C:\bot\imageToSticker-master\index.js:1:28)
>   at Module._compile (internal/modules/cjs/loader.js:1137:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>   at Module.load (internal/modules/cjs/loader.js:985:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ 'C:\bot\imageToSticker-master\index.js' ]
>   }
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! whatsapp-bot-sticker-creator@10.0.0 start: `node index.js`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the whatsapp-bot-sticker-creator@10.0.0 start script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>   npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> itu knp ?

Masalah Dari Indexnya Kayanya

**Comment by YogaSakti** [comment]
`sudo npm install`

**Comment by NewakunGithub** [comment]
Bang ini knp ya masa kaya gini 👇👇

node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /storage/emulated/0/AlphaBot/settings.js
- /storage/emulated/0/AlphaBot/zeeone.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/storage/emulated/0/AlphaBot/settings.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/storage/emulated/0/AlphaBot/settings.js',
    '/storage/emulated/0/AlphaBot/zeeone.js'
  ]
}
