### ISSUE TITLE
Session is Invalid. Retrying

### ISSUE THREAD

**Issue by andraeka** [YogaSakti/imageToSticker#74]
√ Authenticate to continue
√ Loading QR
√ WAPI Reinjected
× The session is invalid. Retrying

**Comment by andraeka** [comment]
Authenticate to continue
(node:2656) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (D:\Aplikasi\wassap\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:195:35)
    at ExecutionContext._evaluateInternal (D:\Aplikasi\wassap\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (D:\Aplikasi\wassap\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:27)
    at DOMWorld.evaluate (D:\Aplikasi\wassap\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:79:24)
(node:2656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
   Authenticate to continue
�  Authenticate to continue▄                                                                                            √ Loading QR

**Comment by rebahanelite** [comment]
udah diupdate @open-wa/wa-automatenya?

**Comment by fadhil050804** [comment]
ketik `npm update`

**Comment by fadlurhmn** [comment]
> √ Authenticate to continue
> √ Loading QR
> √ WAPI Reinjected
> × The session is invalid. Retrying

npm update

**Comment by andraeka** [comment]
alright.. Thanks guys 💯
